spring.jpa.hibernate.ddl-auto=update
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=oms123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

jwt.secret=Rfok+jCPCD3fR0Bau5FPRrt/+I5g8S+k37pdUWP/6m4=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=snehajpatil624@gmail.com
spring.mail.password=fejl hpca qvqd zmsz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
