spring:
  application:
      name: backend

#default profile
---
spring:
  config:
    activate:
      on-profile: default
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/ecommerce_backend
  username: spring_user
  password: sonab@26
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format-sql: true
      open-view: false
  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE